# Generated by Django 4.2.16 on 2024-11-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stocks_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
    ]
