# Generated by Django 4.2.16 on 2024-11-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmentsPortfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='ticker_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
