# Generated by Django 4.2.16 on 2024-11-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
