# Generated by Django 4.2.16 on 2024-11-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
